# Generated by Django 5.2.7 on 2025-10-29 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto'), ('Outro', 'Outro')], default='Carro', max_length=10)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa')),
            ],
        ),
    ]
