# Generated by Django 5.2.7 on 2025-11-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'Veiculo', 'verbose_name_plural': 'Veiculos'},
        ),
    ]
