# Generated by Django 5.2.7 on 2025-11-12 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0002_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(choices=[('PIX', 'Pix'), ('CARTAO', 'Cartão'), ('DINHEIRO', 'Dinheiro')], default='PIX', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('movimentacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='estacionamento.movimentacao')),
            ],
        ),
    ]
