# Generated by Django 5.2.7 on 2025-10-29 19:01

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(help_text='Número de telefone', max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='Endereço de e-mail', max_length=100, verbose_name='E-mail')),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoa.pessoa')),
                ('cpf', models.CharField(help_text='Cpf da pessoa', max_length=14, unique=True, verbose_name='Cpf')),
            ],
            bases=('pessoa.pessoa',),
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoa.pessoa')),
                ('cnpj', models.CharField(help_text='Cnpj da empresa', max_length=14, verbose_name='Cnpj')),
            ],
            bases=('pessoa.pessoa',),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoa.pessoafisica')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='media/funcionarios', variations={}, verbose_name='Foto')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário')),
                ('data_admissao', models.DateField(verbose_name='Data de admissão')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data de demissão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('gerente', models.BooleanField(default=False, verbose_name='Gerente')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
            bases=('pessoa.pessoafisica',),
        ),
    ]
