# Generated by Django 5.2.7 on 2025-10-16 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(help_text='Número de telefone', max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='Endereço de e-mail', max_length=100, verbose_name='E-mail')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cpf', models.CharField(help_text='Cpf da pessoa', max_length=14, verbose_name='Cpf')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(help_text='Número de telefone', max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='Endereço de e-mail', max_length=100, verbose_name='E-mail')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cnpj', models.CharField(help_text='Cnpj da empresa', max_length=14, verbose_name='Cnpj')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCliente', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Juridica')], max_length=2, verbose_name='Tipo')),
                ('pessoa_fisica', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_pf', to='pessoa.pessoafisica')),
                ('pessoa_juridica', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_pj', to='pessoa.pessoajuridica')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
