# Generated by Django 5.2.7 on 2025-11-19 01:48

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='funcionarios', variations={}, verbose_name='Foto'),
        ),
    ]
