# Generated by Django 5.2.7 on 2025-10-16 23:34

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoa.pessoafisica')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='funcionarios/', variations={}, verbose_name='Foto')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário')),
                ('data_admissao', models.DateTimeField(verbose_name='Data de admissão')),
                ('data_demissao', models.DateTimeField(blank=True, null=True, verbose_name='Data de demissão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('gerente', models.BooleanField(default=False, verbose_name='Gerente')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
            bases=('pessoa.pessoafisica',),
        ),
    ]
