# Generated by Django 5.2.7 on 2025-10-18 12:25

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='media/funcionarios', variations={}, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(help_text='Cpf da pessoa', max_length=14, unique=True, verbose_name='Cpf'),
        ),
    ]
