# Generated by Django 5.2.7 on 2025-10-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_alter_funcionario_foto_alter_pessoafisica_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(verbose_name='Data de admissão'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_demissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de demissão'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
